### ISSUE TITLE
Feature Request: Add Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by rupaoruganti** [Swastik007sharma/CampusTrack#14]
Currently, the app uses a single light-themed interface. Adding support for Dark Mode would enhance accessibility, reduce eye strain for users in low-light environments, and improve overall user experience.

Tasks:

Add a dark mode theme (CSS variables or Tailwind + dark: variants if using Tailwind)
Implement a toggle switch to switch between light and dark modes
Please assign this issue to me. I would like to work on implementing dark/light mode for the project.

**Comment by Swastik007sharma** [comment]
Are you sure you can do it? It is going to be a difficult one.

**Comment by rupaoruganti** [comment]
yes i can work on it

**Comment by Swastik007sharma** [comment]
Ensure you pull the latest changes. I have fixed some package incompatibility issues.

**Comment by Swastik007sharma** [comment]
@rupaoruganti Are you still working on it?

**Comment by deepanshu-prajapati01** [comment]
Hi @Swastik007sharma i would like to take on this issue because its like a very very important issue

**Comment by Swastik007sharma** [comment]
> Hi [@Swastik007sharma](https://github.com/Swastik007sharma) i would like to take on this issue because its like a very very important issue

Someone who was working on it already applied the changes. Check the website first. If you want to add some more features, then explain them briefly. I will assign you

**Comment by deepanshu-prajapati01** [comment]
Hey @Swastik007sharma,
Yeah, the theme toggle is working fine, but the current setup isn’t very dev-friendly. Right now, we’re still using custom CSS for dark mode, which kind of defeats the purpose of having Tailwind CSS in the project.

Tailwind already provides a `dark:` class strategy, which is much cleaner and easier to manage. But in the code, I still see a separate CSS file with dark mode variables. I’ll update the Tailwind config to use the `dark` class properly and refactor the app to replace all that custom CSS with Tailwind utility classes.

Also, I’ve opened a PR (https://github.com/Swastik007sharma/CampusTrack/pull/50). Have a look when you get time!

**Comment by Swastik007sharma** [comment]
> Hey [@Swastik007sharma](https://github.com/Swastik007sharma), Yeah, the theme toggle is working fine, but the current setup isn’t very dev-friendly. Right now, we’re still using custom CSS for dark mode, which kind of defeats the purpose of having Tailwind CSS in the project.
> 
> Tailwind already provides a `dark:` class strategy, which is much cleaner and easier to manage. But in the code, I still see a separate CSS file with dark mode variables. I’ll update the Tailwind config to use the `dark` class properly and refactor the app to replace all that custom CSS with Tailwind utility classes.
> 
> Also, I’ve opened a PR ([#50](https://github.com/Swastik007sharma/CampusTrack/pull/50)). Have a look when you get time!

I will review it at night
